# Generated by Django 4.2.1 on 2023-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_photo_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="photo",
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
