# Generated by Django 4.2.1 on 2023-05-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_ticket_delete_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="starred",
        ),
    ]
