# Generated by Django 4.2.1 on 2023-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_ticket_starred"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="date_created",
            new_name="time_created",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="content",
        ),
        migrations.AddField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
