# Generated by Django 4.2.1 on 2023-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
