# Generated by Django 4.2.1 on 2023-06-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_review_time_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="time_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
